Forward events for "Incomplete Control" collection
ArtBlocks/artbot pull request #179
Opened 2022-01-06 20:15 UTC by jonkensta

@thobbs expressed interest  in seeing discord sales events for his latest collection [Incomplete Control](https://www.artblocks.io/project/228). This PR is an attempt to accomplish this by adding a "ic-sales" channel within `ProjectConfig/channels.json` and corresponding activity dispatch cases within `triageActivityMessage()`.

I appreciate your consideration and feedback.

Notes: 
- I used the acronym "IC" for "Incomplete Control" where possible to conform to the existing `icBot` naming.
- This change is simple enough but is currently untested.
- The "ic-sales" channel number is currently the same as "fidenza-sales" but could change in the future.

2022-01-06 20:26 UTC, jakerockland approved these changes
This LGTM, thank you very much for your contribution!

Mind providing a second set of eyes @ryley-o ?

2022-01-06 22:36 UTC, ryley-o requested changes
Thanks for the PR!

A few changes suggested because duplicate json keys (the same channel ID) will cause fidenza-sales to be overwritten, so we can combine them into one channel for now. Can always split up in the future if Tyler wants them to go to separate channels :)

2022-01-06 22:36 UTC, ryley-o commented on Utils/activityTriager.js
> +        bot.channels.cache.get(CHANNEL_IC_SALES).send(embed);
```suggestion
        bot.channels.cache.get(CHANNEL_FIDENZA_AND_IC_SALES).send(embed);
```

2022-01-06 22:36 UTC, ryley-o commented on Utils/activityTriager.js
> +  projectConfig.chIdByName['ic-sales'];
```suggestion
const CHANNEL_FIDENZA_AND_IC_SALES =
  projectConfig.chIdByName['fidenza-and-ic-sales'];
```

2022-01-06 22:36 UTC, ryley-o commented on Utils/activityTriager.js
>    projectConfig.chIdByName['fidenza-sales'];
```suggestion
```

2022-01-06 22:36 UTC, ryley-o commented on Utils/activityTriager.js
>          bot.channels.cache.get(CHANNEL_FIDENZA_SALES).send(embed);
```suggestion
        bot.channels.cache.get(CHANNEL_FIDENZA_AND_IC_SALES).send(embed);
```

2022-01-06 22:36 UTC, ryley-o commented on Utils/activityTriager.js
>          bot.channels.cache.get(CHANNEL_FIDENZA_SALES).send(embed);
```suggestion
        bot.channels.cache.get(CHANNEL_FIDENZA_AND_IC_SALES).send(embed);
```

2022-01-06 22:36 UTC, ryley-o commented on Utils/activityTriager.js
> +        bot.channels.cache.get(CHANNEL_IC_SALES).send(embed);
```suggestion
        bot.channels.cache.get(CHANNEL_FIDENZA_AND_IC_SALES).send(embed);
```

2022-01-06 22:36 UTC, ryley-o commented on ProjectConfig/channels.json
>          "name": "fidenza-sales"
```suggestion
        "name": "fidenza-and-ic-sales"
```

2022-01-06 22:36 UTC, ryley-o commented on ProjectConfig/channels.json
> +        "name": "ic-sales"
```suggestion
```
Having two identical json keys will overwrite `fidenza-sales` on load 😅 

Since one channel will handle both fidenza and ic, can we just rename the channel "fidenza-sales" to be "fidenza-and-ic-sales?

2022-01-06 23:15 UTC, jonkensta commented on ProjectConfig/channels.json
> +        "name": "ic-sales"
> Having two identical json keys will overwrite fidenza-sales on load sweat_smile

Doh! Good catch.

2022-01-06 23:41 UTC, jonkensta commented
> A few changes suggested because duplicate json keys (the same channel ID) will cause fidenza-sales to be overwritten, so we can combine them into one channel for now.

Thank you for this. I implemented all of your suggestions in a new commit.

> Can always split up in the future if Tyler wants them to go to separate channels :)

Roger that. Thank you!

2022-01-07 00:15 UTC, jonkensta commented on Utils/activityTriager.js
>        }
It's possible with these two `if` statements that the Fidenza and IC channel could be forwarded to twice if the collection included both "Fidenza" and "Incomplete Control". I think it's reasonable to assume that these are mutually exclusive cases, however, and find it more readable than using a single `if` with an `||`.

2022-01-07 17:09 UTC, ryley-o commented on Utils/activityTriager.js
>        }
good call!

2022-01-07 17:29 UTC, ryley-o approved these changes
LGTM!

2022-01-07 18:36 UTC, merged

2022-01-07 19:06 UTC, jonkensta commented
Thanks for y'all's help with this!

2022-01-07 19:10 UTC, jakerockland commented
Likewise, thank you both!! :) @jonkensta for the contribution and @ryley-o for the great feedback here.