Add LooksRare API Polling
ArtBlocks/artbot pull request #261
Opened 2022-05-02 22:07 UTC by grantoesterling

## What's New
LooksRare API Polling!
- Artbot will poll LooksRare API every 20 seconds (tentative number, just felt like a happy medium)
- Polls the 25 most recent Sales/Listings for OG/V2 contracts 
-- 4 endpoints
- For each endpoint, it keeps track of the latest event timestamp-wise, and will only report events to Discord if they are newer than the last batch of events it saw

Also added infrastructure to make it easier to add other API Polling bots in the future!

## Screenshots!
Visually the embeds are identical to the current OS ones - just with an added "LooksRare" note in the seller field
Listings:
<img width="456" alt="Screen Shot 2022-05-02 at 5 04 28 PM" src="https://user-images.githubusercontent.com/18132641/166334847-034f742f-4303-4ce9-9258-eb6536f3e92e.png">

Sales:
<img width="465" alt="Screen Shot 2022-05-02 at 5 05 34 PM" src="https://user-images.githubusercontent.com/18132641/166334952-3f894083-65e7-4211-aba4-02142ae1aff7.png">

2022-05-02 22:10 UTC, grantoesterling commented
Apologies for some of these whitespace changes - changes my local Prettier config made that the eslint did not convert back

2022-05-02 22:43 UTC, jakerockland requested changes
This is awesome 🔥 💯 

Have some requested changes below, but this is definitely trending in the right direction and looks great thus far.

2022-05-02 22:43 UTC, jakerockland commented on Classes/ApiPollBot.js
> +class LooksRareApiPollBot extends ApiPollBot {
@grantoesterling Thank you very much for making `ApiPollBot` an abstract parent class. 

Could you please move this `LooksRareApiPollBot` implementation to its own implementation file vs. living in the same file as the parent class? Also, nit, can we please use `LooksRareAPIPollBot`.

2022-05-02 22:43 UTC, jakerockland commented on Classes/ApiPollBot.js
> +class ApiPollBot {
Nit: I would prefer `APIPollBot` here.

2022-05-02 22:43 UTC, jakerockland commented on index.js
> +const pollTime = 20000;
Nit: prefer we make this `API_POLL_TIME` and define at top of file.

2022-05-02 22:43 UTC, jakerockland commented on Utils/activityTriager.js
> +  // // Forward all Chromie Squiggles sales on to the DAO.
Nit: we have an extra `//` here.

2022-05-02 22:43 UTC, jakerockland commented on Utils/activityTriager.js
> +async function triageLooksRareMessage(msg, bot) {
I feel like this functionality should be mostly owned by `LooksRareApiPollBot`, can we refactor to have the `ApiPollBot` conforming-instance be responsible for ineligibly sorting out the incoming message meaning and providing that via a standard interface that can then be triaged via  `sendEmbedToSaleChannels`/`sendEmbedToListChannels`?

2022-05-03 17:39 UTC, Jbern16 approved these changes

2022-05-03 20:57 UTC, jakerockland approved these changes
Fantastic, thank you very much for the updates @grantoesterling

2022-05-03 21:02 UTC, jakerockland commented
LGTM to merge–this is really exciting work.

Reminder that we have to do these deployments manually for now, a'la the convo here: https://discord.com/channels/822311470133542912/930922401808670780/968562463366848513

2022-05-03 21:02 UTC, merged