Archipelago bot: add support for ens addresses
ArtBlocks/artbot pull request #301
Opened 2022-07-14 07:58 UTC by decentralion

When buyers/sellers have an ENS reverse record set, it will now display
their ens name, as in dandelion.eth

2022-07-14 20:41 UTC, Asupkay requested changes

2022-07-14 20:41 UTC, Asupkay commented on Utils/ens.js
> +async function lookupAddress(provider, address) {
Instead of contacting the contract directly you should be able to save some code by using the lookupAddress function from the provider see: https://docs.ethers.io/v5/single-page/#/v5/api/providers/provider/-%23-Provider-lookupAddress

2022-07-14 20:41 UTC, Asupkay commented on Utils/ens.js
> +async function lookupAddress(provider, address) {
Otherwise looks good to me thanks for implementing this!

2022-07-22 16:50 UTC, grantoesterling commented
Done here - https://github.com/ArtBlocks/artbot/pull/307

2022-07-22 16:50 UTC, closed without merging