Archipelago bot: don't show PBAB trades
ArtBlocks/artbot pull request #302
Opened 2022-07-14 08:43 UTC by decentralion

This seems consistent with ArtBot (can't find any Parnassus sales in
block talk, etc)

2022-07-14 20:27 UTC, Asupkay requested changes

2022-07-14 20:27 UTC, Asupkay commented on Classes/ArchipelagoBot.js
> +const AB_LEGACY_CONTRACT = '0x059EDD72Cd353dF5106D2B9cC5ab83a52287aC3a'
Instead of adding the contracts can you import the contract object here?https://github.com/ArtBlocks/artbot/blob/3856691357d3115ac58bfc5bbe8e8481f6fdfef1/ProjectConfig/coreContracts.json

2022-07-14 20:43 UTC, Asupkay approved these changes
Besides the nit this looks good to me so I'm going to approve so you don't have to wait for me once you make the change.

2022-07-16 21:24 UTC, decentralion commented on Classes/ArchipelagoBot.js
> +const AB_LEGACY_CONTRACT = '0x059EDD72Cd353dF5106D2B9cC5ab83a52287aC3a'
Done!

2022-07-16 23:45 UTC, Asupkay approved these changes

2022-07-16 23:45 UTC, merged