Adding collection to lists and sales
ArtBlocks/artbot pull request #364
Opened 2022-09-23 23:39 UTC by grantoesterling

## What's New
- Adding Curation Status to list/sales events

<img width="628" alt="Screen Shot 2022-09-23 at 5 37 28 PM" src="https://user-images.githubusercontent.com/18132641/192069714-df153162-13e0-47c3-a8a6-b0d5636b92db.png">

2022-09-26 14:01 UTC, Jbern16 requested changes

2022-09-26 14:01 UTC, Jbern16 commented on Classes/APIBots/ReservoirListBot.js
> +      ? artBlocksData.curation_status[0].toUpperCase() +
should be using vertical_name here instead

2022-09-27 15:17 UTC, mchrupcala approved these changes

2022-09-27 15:22 UTC, grantoesterling commented on Classes/APIBots/ReservoirListBot.js
> +      ? artBlocksData.curation_status[0].toUpperCase() +
@Jbern16 the token API doesn't have `vertical_name`, it has `curation_status`

2022-09-27 15:31 UTC, Jbern16 approved these changes

2022-09-27 15:32 UTC, merged